blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/JoJo275/simple-python-boilerplate#readme
    about: Check the README for setup and usage instructions
