# =============================================================================
# config.yml can be used to generate buttons on the issue template selection on GitHub.
# This can reduce developer workload by directing users to relevant resources
# before they create an issue.
#
# Basically giving users the correct tools instead of creating an unwarranted issue
# if the information is already available elsewhere.
# ==============================================================================

blank_issues_enabled: false

contact_links:
  - name: ðŸ“– Documentation (Usage)
    url: https://github.com/JoJo275/simple-python-boilerplate#readme
    about: Start here â€” setup, installation, and usage instructions.

  - name: ðŸ’¬ Discussions (Q&A)
    url: https://github.com/JoJo275/simple-python-boilerplate/discussions
    about: Have a question or need help? Ask here instead of opening an issue


